version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: booksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend/book/book
      dockerfile: ../../Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/booksdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    build: ./frontend/book-app
    ports:
      - "4200:4200"
    depends_on:
      - backend